name: Trigger wheel build

on:
  push:
    branches: [master, 'release*']
    tags: ['*']

permissions:
  contents: read

jobs:
  build-wheels:
    if: github.repository == 'python/mypy'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2.3.4
        with:
          python-version: '3.7'
      - name: Trigger script
        env:
          WHEELS_PUSH_TOKEN: ${{ secrets.WHEELS_PUSH_TOKEN }}
        run: ./misc/trigger_wheel_build.sh
