name: Check documentation build

on:
  push:
    branches: [master, 'release*']
    tags: ['*']
  pull_request:
    paths:
    - 'docs/**'
    - '**/*.rst'
    - '**/*.md'
    - CREDITS
    - LICENSE

jobs:
  docs:
    runs-on: ubuntu-latest
    env:
      TOXENV: docs
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2.3.4
        with:
          python-version: '3.7'
      - name: Install tox
        run: pip install --upgrade 'setuptools!=50' 'virtualenv<16.7.11' tox==3.20.1
      - name: Setup tox environment
        run: tox -e ${{ env.TOXENV }} --notest
      - name: Test
        run: tox -e ${{ env.TOXENV }} --skip-pkg-install
